inherit_gem:
  rubocop-govuk:
    - config/default.yml

AllCops:
  TargetRubyVersion: 2.4

Naming/FileName:
  Exclude:
    # RuboCop wants this to be renamed to `lib/gds_api_adapters.rb`. But I don't
    # know what effect that'll have on the rest of this gem and don't particularly
    # have the brain to find out. So I'm ignoring it for now. -- Issy, 2020-05.
    - lib/gds-api-adapters.rb
